[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "apscheduler==3.10.4",
    "nest-asyncio>=1.6.0",
    "openai>=1.30.0",
    "python-telegram-bot==21.4",
    "telegram>=0.0.1",
]
